name: Merge Development into Main

on:
  push:
    branches:
      - Development

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge changes
        run: |
          git config --global user.name "CI"
          git config --global user.email "ci@example.com"

          git checkout main
          git merge --no-commit --strategy-option=ours Development
          git checkout HEAD -- wp_config.php
          git commit -m "Merge Development into Main (excluding wp_config.php)"
          git push origin main
